# Database Configuration for Vytal Backend
# Copy this file to Config.toml and update with your actual database credentials

[backend.database]
dbHost = ""
dbPort = 3307
dbDatabase = ""
dbUser = ""
dbPassword = ""